---- Flyway migration script: V2 -- Seed Initial Data
--
---- 1. Inserir usuários usando a coluna 'login' e o hash real da senha "password"
--INSERT INTO users (login, name, password, role) VALUES
--('admin', 'Admin do Sistema', '$2a$10$3yT89DbD1I0aLrn.3sAUg.WXYx5yV50Et2bE6l1aE9o2o8mAYNgHe', 'ADMIN'),
--('gestor', 'Gestor de Contratos', '$2a$10$3yT89DbD1I0aLrn.3sAUg.WXYx5yV50Et2bE6l1aE9o2o8mAYNgHe', 'GESTOR'),
--('engenheiro', 'Fulano de Tal', '$2a$10$3yT89DbD1I0aLrn.3sAUg.WXYx5yV50Et2bE6l1aE9o2o8mAYNgHe', 'ENGENHEIRO'),
--('fiscal', 'Ciclano da Silva', '$2a$10$3yT89DbD1I0aLrn.3sAUg.WXYx5yV50Et2bE6l1aE9o2o8mAYNgHe', 'FISCAL'),
--('cliente', 'Cliente Final', '$2a$10$3yT89DbD1I0aLrn.3sAUg.WXYx5yV50Et2bE6l1aE9o2o8mAYNgHe', 'USER')
--ON CONFLICT (login) DO NOTHING;
--
---- 2. Popular as listas pré-definidas (sem alterações)
--INSERT INTO equipamentos (nome) VALUES ('Betoneira'), ('Caminhão Basculante'), ('Retroescavadeira'), ('Outro');
--INSERT INTO maos_de_obra (nome) VALUES ('Engenheiro'), ('Encarregado'), ('Servente'), ('Outro');
--INSERT INTO servicos (nome, unidade_medida) VALUES ('Escavação', 'm³'), ('Montagem de viga', 'un'), ('Concretagem', 'm³'), ('Outro', 'un');
--
---- 3. Inserir uma Obra de exemplo
--INSERT INTO obras (contratante, contratada, projeto, status, fiscal_id) VALUES
--('Prefeitura de Anápolis', 'Hefesto Construções', 'Construção da Ponte Central', 'ATIVA', (SELECT id from users where login = 'fiscal'));
--
---- 4. Vincular o engenheiro à obra
--INSERT INTO obras_engenheiros (obra_id, engenheiro_id) VALUES
--((SELECT id from obras where projeto = 'Construção da Ponte Central'), (SELECT id from users where login = 'engenheiro'));
--
---- 5. Inserir um Diário de Obra de exemplo
--INSERT INTO diarios_de_obra (
--    obra_id,
--    data,
--    condicao_climatica,
--    observacoes,
--    status,
--    autor_id
--) VALUES (
--    (SELECT id from obras where projeto = 'Construção da Ponte Central'),
--    CURRENT_DATE - INTERVAL '1 day',
--    'Tempo Bom',
--    'Nenhuma observação adicional.',
--    'AGUARDANDO_AVALIACAO',
--    (SELECT id from users where login = 'engenheiro')
--);
--
---- 6. Associar os itens ao diário criado
--INSERT INTO diario_maos_de_obra (diario_id, mao_de_obra_id, quantidade) VALUES
--((SELECT id FROM diarios_de_obra WHERE data = CURRENT_DATE - INTERVAL '1 day'), (SELECT id FROM maos_de_obra WHERE nome = 'Engenheiro'), 1),
--((SELECT id FROM diarios_de_obra WHERE data = CURRENT_DATE - INTERVAL '1 day'), (SELECT id FROM maos_de_obra WHERE nome = 'Servente'), 8);
--
--INSERT INTO diario_equipamentos (diario_id, equipamento_id, quantidade) VALUES
--((SELECT id FROM diarios_de_obra WHERE data = CURRENT_DATE - INTERVAL '1 day'), (SELECT id FROM equipamentos WHERE nome = 'Betoneira'), 1);
--
--INSERT INTO diario_servicos (diario_id, servico_id, quantidade) VALUES
--((SELECT id FROM diarios_de_obra WHERE data = CURRENT_DATE - INTERVAL '1 day'), (SELECT id FROM servicos WHERE nome = 'Montagem de viga'), 1);
--
--INSERT INTO diario_fotos (diario_id, foto_url) VALUES
--((SELECT id FROM diarios_de_obra WHERE data = CURRENT_DATE - INTERVAL '1 day'), 'storage/obra_1/foto_viga.jpg');
--
--INSERT INTO diario_visitas (diario_id, visita_registro) VALUES
--((SELECT id FROM diarios_de_obra WHERE data = CURRENT_DATE - INTERVAL '1 day'), 'Visita do engenheiro fiscal da prefeitura.');